name: Lint workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Install Dependencies
        run: npm install

      - name: Run JavaScript linter
        run: npm run lint:js

      - name: Run Stylelint linter
        run: npm run lint:scss
